### PR TITLE
support for utm_content and utm_term

### PR DESCRIPTION
**Pull request by dirkkelly**
Adds support for two additional utm_ attributes, content and term.

http://www.terminusapp.com/blog/7-faqs-about-utm-parameters/

### CODE REVIEW

**Comment by joshuapaling** [comment]
Sweet, thanks. I'll take a look at this within the next day or two. Hassle me again if it's not merged within a few days.

**Comment by joshuapaling** [comment]
Merged. Thanks for those new attributes, and also for the other tidy ups!

**Comment by joshuapaling** [comment]
BTW, I've bumped the version to 0.1.2 in case you want to use your changes.

**Comment by dirkkelly** [comment]
Thanks @joshuapaling, really appreciate this gem.

**Pull request merged**
