### PR TITLE
defines valid_request

### PR DESCRIPTION
**Pull request by dirkkelly**
We'd like to track source/medium even if campaign is not present.

This refactor will give us a simple way to unobtrusively alter the required params.

### CODE REVIEW

**Comment by joshuapaling** [comment]
I'll take a deeper look at this soon. I just want to try remember what reason I had for rejecting when campaign isn't present - cos perhaps I didn't have one, in which case, we should just get rid of it.

Also, if it's likely to vary a lot, we should just make 'required params' a config option.

If I don't merge this within a couple of days, please remind me.

**Comment by joshuapaling** [comment]
Merging this now because I haven't had a chance to look into better solutions yet. Probably it should be a configuration item so people can change it without altering the class. But I'll look into that another time. Thanks for the PR!

**Comment by dirkkelly** [comment]
Cheers. Agreed on the configuration. Will submit pr if I get to it.

**Comment by joshuapaling** [comment]
Thanks!

Dirk Kelly wrote:

**Pull request merged**
